apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataops-preprocess
spec:
  schedule: "0 * * * *" # Every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: preprocess
            image: nikitamathur/online-sales-dashboard:latest
            command: ["python", "scripts/preprocess_data.py"]
            env:
            - name: KAGGLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kaggle-secret
                  key: KAGGLE_USERNAME
            - name: KAGGLE_KEY
              valueFrom:
                secretKeyRef:
                  name: kaggle-secret
                  key: KAGGLE_KEY
          restartPolicy: OnFailure
