apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataops-preprocess
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: preprocess
            image: nikitamathur/online-sales-dashboard:latest
            command: ["python", "scripts/preprocess_data.py"]
          restartPolicy: OnFailure
