apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataops
  template:
    metadata:
      labels:
        app: dataops
    spec:
      containers:
      - name: dataops-container
        image: nikitamathur/online-sales-dashboard:latest
        ports:
        - containerPort: 8080
