name: Deploy Dashboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # This schedule runs the job every hour

env:
  KUBECONFIG: /home/runner/.kube/config

jobs:
  preprocess_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Data Processing & Cleanup
      run: python scripts/preprocess_data.py
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

  build_image:
    runs-on: ubuntu-latest
    needs: preprocess_data
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t nikitamathur/online-sales-dashboard:latest .

    - name: Push Docker Image
      run: docker push nikitamathur/online-sales-dashboard:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube and Kubernetes tools
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0
        minikube addons enable ingress

    - name: Create Kubernetes resources
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f cronjob.yaml

    - name: Verify Deployment
      run: kubectl get pods

  check_updates:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Set up Minikube and Kubernetes tools
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0
        minikube addons enable ingress

    - name: Wait for CronJob to be Ready
      run: |
        kubectl get cronjob dataops-preprocess || kubectl apply -f cronjob.yaml

    - name: Create Job from CronJob to Check for Updates
      run: kubectl create job --from=cronjob/dataops-preprocess manual-preprocess-job

    - name: Wait for Job to Complete
      run: kubectl wait --for=condition=complete job/manual-preprocess-job --timeout=120s
