name: Deploy Dashboard

on:
  push:
    branches:
      - main

jobs:
  fetch_and_process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: pip install kaggle pandas

      - name: Create data directory
        run: mkdir -p data

      - name: Fetch & Process Data
        run: |
          python scripts/preprocess_data.py
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

  build:
    runs-on: ubuntu-latest
    needs: fetch_and_process_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t nikitamathur/online-sales-dashboard:latest .

      - name: Push Docker Image
        run: docker push nikitamathur/online-sales-dashboard:latest

  deploy_dashboard:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube version: 'latest'
          kubernetes version: 'v1.24.0'
          driver: 'docker'

      - name: Start Minikube
        run: minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          minikube kubeconfig > $HOME/.kube/config

      - name: Create Kubernetes resources
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: kubectl get pods

  check_for_updates:
    runs-on: ubuntu-latest
    needs: deploy_dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube version: 'latest'
          kubernetes version: 'v1.24.0'
          driver: 'docker'

      - name: Start Minikube
        run: minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0

      - name: Set up CronJob for Data Updates
        run: kubectl apply -f cronjob.yaml
