name: Deploy Dashboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # This schedule runs the job every hour

env:
  KUBECONFIG: /home/runner/.kube/config

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube, conntrack, crictl, and cri-dockerd
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -Lo crictl.tar.gz https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.24.0/crictl-v1.24.0-linux-amd64.tar.gz
        sudo tar -C /usr/local/bin -xzf crictl.tar.gz
        rm crictl.tar.gz
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        # Install cri-dockerd
        sudo apt-get install -y golang-go
        git clone https://github.com/Mirantis/cri-dockerd.git
        cd cri-dockerd
        mkdir bin
        go get && go build -o bin/cri-dockerd
        sudo cp bin/cri-dockerd /usr/local/bin/
        sudo cp packaging/systemd/* /etc/systemd/system/
        sudo systemctl daemon-reload
        sudo systemctl enable cri-docker.service
        sudo systemctl enable --now cri-docker.socket
        cd ..
        # Start Minikube
        minikube start --driver=none --container-runtime=docker --kubernetes-version=v1.24.0
        minikube addons enable ingress

    - name: Create Job from CronJob to Check for Updates
      run: kubectl create job --from=cronjob/dataops-preprocess manual-preprocess-job

  fetch_data:
    runs-on: ubuntu-latest
    needs: check_updates
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch Data from Kaggle
      run: python download_data.py
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

  process_data:
    runs-on: ubuntu-latest
    needs: fetch_data
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Data Processing & Cleanup
      run: python preprocess_data.py

  build_image:
    runs-on: ubuntu-latest
    needs: process_data
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t nikitamathur/online-sales-dashboard:latest .

    - name: Push Docker Image
      run: docker push nikitamathur/online-sales-dashboard:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube, conntrack, crictl, and cri-dockerd
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -Lo crictl.tar.gz https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.24.0/crictl-v1.24.0-linux-amd64.tar.gz
        sudo tar -C /usr/local/bin -xzf crictl.tar.gz
        rm crictl.tar.gz
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        # Install cri-dockerd
        sudo apt-get install -y golang-go
        git clone https://github.com/Mirantis/cri-dockerd.git
        cd cri-dockerd
        mkdir bin
        go get && go build -o bin/cri-dockerd
        sudo cp bin/cri-dockerd /usr/local/bin/
        sudo cp packaging/systemd/* /etc/systemd/system/
        sudo systemctl daemon-reload
        sudo systemctl enable cri-docker.service
        sudo systemctl enable --now cri-docker.socket
        cd ..
        # Start Minikube
        minikube start --driver=none --container-runtime=docker --kubernetes-version=v1.24.0
        minikube addons enable ingress

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f cronjob.yaml

    - name: Verify Deployment
      run: kubectl get pods
