name: Deploy Dashboard

on:
  push:
    branches:
      - main

jobs:
  fetch_and_process_data:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install kaggle pandas

      - name: Fetch & Process Data
        run: python scripts/preprocess_data.py
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

  build:
    runs-on: self-hosted
    needs: fetch_and_process_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t nikitamathur/online-sales-dashboard:latest .

      - name: Push Docker Image
        run: docker push nikitamathur/online-sales-dashboard:latest

  deploy_dashboard:
    runs-on: self-hosted
    needs: build
    env:
      KUBECONFIG: ${{ github.workspace }}/.kube/config
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube and Kubernetes tools
        run: |
          minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0
          minikube addons enable ingress

      - name: Set up Kubeconfig
        run: |
          mkdir -p ${{ github.workspace }}/.kube
          cp /Users/nik/.kube/config ${{ github.workspace }}/.kube/config

      - name: Create Kubernetes resources
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: kubectl get pods

  check_for_updates:
    runs-on: self-hosted
    needs: deploy_dashboard
    env:
      KUBECONFIG: ${{ github.workspace }}/.kube/config
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube and Kubernetes tools
        run: |
          minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0

      - name: Set up CronJob for Data Updates
        run: kubectl apply -f cronjob.yaml
