name: Deploy Dashboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # This schedule runs the job every hour

env:
  KUBECONFIG: /home/runner/.kube/config

jobs:
  preprocess_data:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Data Processing & Cleanup
        run: python scripts/preprocess_data.py
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

  build_image:
    runs-on: self-hosted
    needs: preprocess_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t nikitamathur/online-sales-dashboard:latest .

      - name: Push Docker Image
        run: docker push nikitamathur/online-sales-dashboard:latest

  deploy:
    runs-on: self-hosted
    needs: build_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube and Kubernetes tools
        run: |
          minikube start --driver=docker --container-runtime=docker --kubernetes-version=v1.24.0
          minikube addons enable ingress

      - name: Create Kubernetes resources
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f cronjob.yaml

      - name: Verify Deployment
        run: kubectl get pods
